<?php

use Illuminate\Database\Seeder;

class BanksTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('banks')->insert([
            array('bank_code' => '001', 'bank_name' => 'Banco do Brasil'),
            array('bank_code' => '003', 'bank_name' => 'Banco da Amazônia'),
            array('bank_code' => '004', 'bank_name' => 'Banco do Nordeste'),
            array('bank_code' => '021', 'bank_name' => 'Banestes'),
            array('bank_code' => '025', 'bank_name' => 'Banco Alfa'),
            array('bank_code' => '027', 'bank_name' => 'Besc'),
            array('bank_code' => '029', 'bank_name' => 'Banerj'),
            array('bank_code' => '031', 'bank_name' => 'Banco Beg'),
            array('bank_code' => '033', 'bank_name' => 'Banco Santander Banespa'),
            array('bank_code' => '036', 'bank_name' => 'Banco Bem'),
            array('bank_code' => '037', 'bank_name' => 'Banpará'),
            array('bank_code' => '038', 'bank_name' => 'Banestado'),
            array('bank_code' => '039', 'bank_name' => 'BEP'),
            array('bank_code' => '040', 'bank_name' => 'Banco Cargill'),
            array('bank_code' => '041', 'bank_name' => 'Banrisul'),
            array('bank_code' => '044', 'bank_name' => 'BVA'),
            array('bank_code' => '045', 'bank_name' => 'Banco Opportunity'),
            array('bank_code' => '047', 'bank_name' => 'Banese'),
            array('bank_code' => '062', 'bank_name' => 'Hipercard'),
            array('bank_code' => '063', 'bank_name' => 'Ibibank'),
            array('bank_code' => '065', 'bank_name' => 'Lemon Bank'),
            array('bank_code' => '066', 'bank_name' => 'Banco Morgan Stanley Dean Witter'),
            array('bank_code' => '069', 'bank_name' => 'BPN Brasil'),
            array('bank_code' => '070', 'bank_name' => 'Banco de Brasília – BRB'),
            array('bank_code' => '072', 'bank_name' => 'Banco Rural'),
            array('bank_code' => '073', 'bank_name' => 'Banco Popular'),
            array('bank_code' => '074', 'bank_name' => 'Banco J. Safra'),
            array('bank_code' => '075', 'bank_name' => 'Banco CR2'),
            array('bank_code' => '076', 'bank_name' => 'Banco KDB'),
            array('bank_code' => '096', 'bank_name' => 'Banco BMF'),
            array('bank_code' => '104', 'bank_name' => 'Caixa Econômica Federal'),
            array('bank_code' => '107', 'bank_name' => 'Banco BBM'),
            array('bank_code' => '116', 'bank_name' => 'Banco Único'),
            array('bank_code' => '151', 'bank_name' => 'Nossa Caixa'),
            array('bank_code' => '175', 'bank_name' => 'Banco Finasa'),
            array('bank_code' => '184', 'bank_name' => 'Banco Itaú BBA'),
            array('bank_code' => '204', 'bank_name' => 'American Express Bank'),
            array('bank_code' => '208', 'bank_name' => 'Banco Pactual'),
            array('bank_code' => '212', 'bank_name' => 'Banco Matone'),
            array('bank_code' => '213', 'bank_name' => 'Banco Arbi'),
            array('bank_code' => '214', 'bank_name' => 'Banco Dibens'),
            array('bank_code' => '217', 'bank_name' => 'Banco Joh Deere'),
            array('bank_code' => '218', 'bank_name' => 'Banco Bonsucesso'),
            array('bank_code' => '222', 'bank_name' => 'Banco Calyon Brasil'),
            array('bank_code' => '224', 'bank_name' => 'Banco Fibra'),
            array('bank_code' => '225', 'bank_name' => 'Banco Brascan'),
            array('bank_code' => '229', 'bank_name' => 'Banco Cruzeiro'),
            array('bank_code' => '230', 'bank_name' => 'Unicard'),
            array('bank_code' => '233', 'bank_name' => 'Banco GE Capital'),
            array('bank_code' => '237', 'bank_name' => 'Bradesco'),
            array('bank_code' => '241', 'bank_name' => 'Banco Clássico'),
            array('bank_code' => '243', 'bank_name' => 'Banco Stock Máxima'),
            array('bank_code' => '246', 'bank_name' => 'Banco ABC Brasil'),
            array('bank_code' => '248', 'bank_name' => 'Banco Boavista Interatlântico'),
            array('bank_code' => '249', 'bank_name' => 'Investcred Unibanco'),
            array('bank_code' => '250', 'bank_name' => 'Banco Schahin'),
            array('bank_code' => '252', 'bank_name' => 'Fininvest'),
            array('bank_code' => '254', 'bank_name' => 'Paraná Banco'),
            array('bank_code' => '263', 'bank_name' => 'Banco Cacique'),
            array('bank_code' => '265', 'bank_name' => 'Banco Fator'),
            array('bank_code' => '266', 'bank_name' => 'Banco Cédula'),
            array('bank_code' => '300', 'bank_name' => 'Banco de la Nación Argentina'),
            array('bank_code' => '318', 'bank_name' => 'Banco BMG'),
            array('bank_code' => '320', 'bank_name' => 'Banco Industrial e Comercial'),
            array('bank_code' => '356', 'bank_name' => 'ABN Amro Real'),
            array('bank_code' => '341', 'bank_name' => 'Itau'),
            array('bank_code' => '347', 'bank_name' => 'Sudameris'),
            array('bank_code' => '351', 'bank_name' => 'Banco Santander'),
            array('bank_code' => '353', 'bank_name' => 'Banco Santander Brasil'),
            array('bank_code' => '366', 'bank_name' => 'Banco Societe Generale Brasil'),
            array('bank_code' => '370', 'bank_name' => 'Banco WestLB'),
            array('bank_code' => '376', 'bank_name' => 'JP Morgan'),
            array('bank_code' => '389', 'bank_name' => 'Banco Mercantil do Brasil'),
            array('bank_code' => '394', 'bank_name' => 'Banco Mercantil de Crédito'),
            array('bank_code' => '399', 'bank_name' => 'HSBC'),
            array('bank_code' => '409', 'bank_name' => 'Unibanco'),
            array('bank_code' => '412', 'bank_name' => 'Banco Capital'),
            array('bank_code' => '422', 'bank_name' => 'Banco Safra'),
            array('bank_code' => '453', 'bank_name' => 'Banco Rural'),
            array('bank_code' => '456', 'bank_name' => 'Banco Tokyo Mitsubishi UFJ'),
            array('bank_code' => '464', 'bank_name' => 'Banco Sumitomo Mitsui Brasileiro'),
            array('bank_code' => '477', 'bank_name' => 'Citibank'),
            array('bank_code' => '479', 'bank_name' => 'Itaubank (antigo Bank Boston)'),
            array('bank_code' => '487', 'bank_name' => 'Deutsche Bank'),
            array('bank_code' => '488', 'bank_name' => 'Banco Morgan Guaranty'),
            array('bank_code' => '492', 'bank_name' => 'Banco NMB Postbank'),
            array('bank_code' => '494', 'bank_name' => 'Banco la República Oriental del Uruguay'),
            array('bank_code' => '495', 'bank_name' => 'Banco La Provincia de Buenos Aires'),
            array('bank_code' => '505', 'bank_name' => 'Banco Credit Suisse'),
            array('bank_code' => '600', 'bank_name' => 'Banco Luso Brasileiro'),
            array('bank_code' => '604', 'bank_name' => 'Banco Industrial'),
            array('bank_code' => '610', 'bank_name' => 'Banco VR'),
            array('bank_code' => '611', 'bank_name' => 'Banco Paulista'),
            array('bank_code' => '612', 'bank_name' => 'Banco Guanabara'),
            array('bank_code' => '613', 'bank_name' => 'Banco Pecunia'),
            array('bank_code' => '623', 'bank_name' => 'Banco Panamericano'),
            array('bank_code' => '626', 'bank_name' => 'Banco Ficsa'),
            array('bank_code' => '630', 'bank_name' => 'Banco Intercap'),
            array('bank_code' => '633', 'bank_name' => 'Banco Rendimento'),
            array('bank_code' => '634', 'bank_name' => 'Banco Triângulo'),
            array('bank_code' => '637', 'bank_name' => 'Banco Sofisa'),
            array('bank_code' => '638', 'bank_name' => 'Banco Prosper'),
            array('bank_code' => '643', 'bank_name' => 'Banco Pine'),
            array('bank_code' => '652', 'bank_name' => 'Itaú Holding Financeira'),
            array('bank_code' => '653', 'bank_name' => 'Banco Indusval'),
            array('bank_code' => '654', 'bank_name' => 'Banco A.J. Renner'),
            array('bank_code' => '655', 'bank_name' => 'Banco Votorantim'),
            array('bank_code' => '707', 'bank_name' => 'Banco Daycoval'),
            array('bank_code' => '719', 'bank_name' => 'Banif'),
            array('bank_code' => '721', 'bank_name' => 'Banco Credibel'),
            array('bank_code' => '734', 'bank_name' => 'Banco Gerdau'),
            array('bank_code' => '735', 'bank_name' => 'Banco Pottencial'),
            array('bank_code' => '738', 'bank_name' => 'Banco Morada'),
            array('bank_code' => '739', 'bank_name' => 'Banco Galvão de Negócios'),
            array('bank_code' => '740', 'bank_name' => 'Banco Barclays'),
            array('bank_code' => '741', 'bank_name' => 'BRP'),
            array('bank_code' => '743', 'bank_name' => 'Banco Semear'),
            array('bank_code' => '745', 'bank_name' => 'Banco Citibank'),
            array('bank_code' => '746', 'bank_name' => 'Banco Modal'),
            array('bank_code' => '747', 'bank_name' => 'Banco Rabobank International'),
            array('bank_code' => '748', 'bank_name' => 'Banco Cooperativo Sicredi'),
            array('bank_code' => '749', 'bank_name' => 'Banco Simples'),
            array('bank_code' => '751', 'bank_name' => 'Dresdner Bank'),
            array('bank_code' => '752', 'bank_name' => 'BNP Paribas'),
            array('bank_code' => '753', 'bank_name' => 'Banco Comercial Uruguai'),
            array('bank_code' => '755', 'bank_name' => 'Banco Merrill Lynch'),
            array('bank_code' => '756', 'bank_name' => 'Banco Cooperativo do Brasil'),
            array('bank_code' => '757', 'bank_name' => 'KEB'),
        ]);
    }
}
